[[_msde_ms_demonstration_example]]
= Restcomm Media Server Demonstration Example

Restcomm Media Server 3.0.0.FINAL is a standalone media software.
Control panels servers are required in order to make Restcomm Media Server part of your network architecture.
Two controlling protocols (JSR-309 and MGCP) are currently enabled to work with Restcomm Media Server 3.0.0.FINAL. 

Depending on your needs, https://github.com/Restcomm/jain-slee/[Jain-slee ] , https://github.com/Restcomm/sipservlets/[Sip Servlets ] or https://github.com/Restcomm/Restcomm-Connect/[RestComm-Connect] can be used to control the media server.
The examples below are included in the &Restcomm Media Server_SHORT_NAME; software. 

To get Jain-Slee examples please see following examples that are part of mobicents / telestax jain Slee release :

.Example for Jain-Slee 
[cols="1", frame="all", options="header"]
|===
| Jain-Slee Example List
| call-controller2 which uses MGCP to control
| mgcp-demo which uses MGCP to control
| mscontrol-demo which uses JSR-309 to control
|===

For more information please see https://github.com/RestComm/jain-slee.media/tree/master/examples[Jain-Slee documentation] that comes with this examples. 

The following examples use Restcomm Media Server with Restcomm SIP Servlets :

.Examples for SIP Servlets 
[cols="1", frame="all", options="header"]
|===
| SIP Servlets Example List
| conference-demo jsr-309
| media-jsr-309-servlet
| shopping-demo-jsr309
|===

All servlets examples are using jsr-309 control protocol.

For more information please see https://github.com/RestComm/sip-servlets/tree/master/sip-servlets-examples[SIP Servlets documentation] that comes with these examples. 

.	Using Restcomm Media Server with RestComm 
[cols="1", frame="all", options="header"]
|===
|  with RestComm
| RMS is required in order to successfully work with RestComm. Consequently, any example created to demonstrate the use of RestComm will incorporate Restcomm Media Server (RMS). RestComm use MGCP as the controlling protocol for RMS.
|===

For more information please see https://github.com/Restcomm/Restcomm-Connect[RestComm-Connect documentation.]	
