[[_chapter_installing_the_media_server]]
= Installing the Media Server

The {this-platform} {this-application} is available in both binary and source code distributions.

The simplest way to get started with the Media Server is to download the ready-to-run binary distribution from the https://github.com/RestComm/mediaserver/releases/latest[releases page].
Alternatively, the source code for the Media Server can be obtained by checking it out https://github.com/RestComm/mediaserver[from its repository] using the Git version control system. You can later run a build using Maven.

The binary distribution is recommended for most users.
Downloading and building the source code is recommended for those who want access to the latest revisions and Media Server capabilities.

Installing the <<_jdk_installing_configuring_and_running>>

[[_itms-binary-standalone_media_server-installing_configuring_and_running]]
== Standalone Media Server Binary Distribution

[[_itms_binary_standalone_media_server_preinstall_requirements_and_prerequisites]]
=== Pre-Install Requirements and Prerequisites

Ensure that the following requirements have been met before continuing with the installation:

.Hardware Requirements
Sufficient Disk Space::
Once unzipped, the {this-platform} {this-application} binary release requires _at least_	36Mb of free disk space. Keep in mind that disk space requirements may change in future iterations.

Anything Java Itself Will Run On::
The JBoss embedded Media Server and its bundled servers, JBoss, are 100% Java. The {this-platform} {this-application} will run on the same hardware that the JBoss Application Server runs on.

.Software Requirements
Java Development Kit::
A working installation of JDK 5 or higher is required for {this-platform} {this-application} to run.

[[_itms_binary_standalone_media_server_downloading]]
=== Downloading

The latest version of the {this-platform} {this-application} is available from the project's https://github.com/RestComm/mediaserver/releases/latest[github release page].
Select the link named _restcomm-media-server-<version>.zip_ to start downloading the latest stable binary release from community.

[[_itms_binary_standalone_media_server_installing]]
=== Installing

Once the requirements and prerequisites have been met, the {this-platform} {this-application} can be installed into the system.
Follow the instructions below for the operating system on which the server will reside. 

.Procedure: Installing the {this-platform} {this-application} Binary Distribution on Linux

It is assumed that the downloaded archive is saved in the home directory, and that a terminal window is open displaying the home directory. 

. Create a subdirectory into which the files can be extracted. For ease of identification, it is recommended that the version number of the binary is included in this directory name.
+
----
~]$ mkdir restcomm-media-server-<version>
----

. Move the downloaded zip file into the directory:
+
----
~]$ mv restcomm-media-server-<version>.zip restcomm-media-server-<version>
----

. Move into the directory:
+
----
~]$ cd	restcomm-media-server-<version>
----

. Extract the files into the current directory:
+
----
restcomm-media-server-<version>]$ unzip restcomm-media-server-<version>.zip
----

. Consider deleting the archive, if free disk space is an issue. 
+
----
restcomm-media-server-<version>]$ rm restcomm-media-server-<version>.zip
----

[[_itms_binary_standalone_media_server_running]]
=== Running

Now that the {this-platform} {this-application} binary has been downloaded and properly installed in a local directory, we can bootstrap the project by following these steps:

. Change the working directory to installation directory (the one into which the zip file's contents was extracted) 
+
----
~]$ cd restcomm-media-server-<version>
----

. (Optional) Ensure that the [path]_bin/run.sh_ start script is executable. 
+
----
restcomm-media-server-<version>]$ chmod +x bin/run.sh
----

. Execute the [path]_run.sh_ shell script. 
+
----
restcomm-media-server-<version>]$ ./bin/run.sh
----

[NOTE]
====
Instead of executing the shell script, the [path]_run.jar_ executable Java archive can be executed from the [path]_bin_ directory: 

----
restcomm-media-server-<version>]$ java -jar bin/run.jar
----
====

You can verify that {this-platform} {this-application} has started successfully if the last line of output in the Linux Terminal window is similar to 

[source]
----
15:35:16,897 INFO  [MainDeployer] [[[[[[[[[ RestComm Media Server: release.version=5.0.0-SNAPSHOT Started ]]]]]]]]]
----

[[_itms-binary-standalone_media_server-stopping]]
=== Stopping

To stop the execution of an active {this-platform} {this-application} process, we a couple of possibilities:

. Send interrupt signal (Ctrl+C) to the active Linux Terminal session where {this-platform} {this-application} process is running.

. Find the PID of the {this-platform} {this-application} Java process and kill it:
+
----
~]$ ps aux | grep java
hrosa            10947  16.8 22.4  6603132 3755516 s005  S+    3:51PM   0:07.51 /opt/.jenv/versions/oracle64-1.7.0.79/bin/java -Dprogram.name=run.sh -classpath /opt/restcomm-media-server/bin/run.jar org.mobicents.media.server.bootstrap.Main
~]$ kill 10947
----

[[_itms_standalone_server_structure]]
=== Server Structure

Now that the server is installed, it is important to understand the layout of the server directories.
An understanding of the server structure is useful when deploying examples, and making configuration changes.
It is also useful to understand what components can be removed to reduce the server boot time. 

The directory structure in the {this-platform} {this-application} installation directory is named using a standard structure. <<_tab_mms_jboss_directory_structure>> describes each directory as well as the type of information contained within each location.

[[_tab_mms_jboss_directory_structure]]
.Directory Structure
[cols="1,1", frame="all", options="header"]
|===
| Directory Name | Description
| bin | Contains the entry point JARs and start-up scripts included with the Media Server distribution.
| conf | Contains the core services that are required for the server. This includes the bootstrap descriptor, log files, and the default media server configuration file.
| deploy | Contains the dynamic deployment content required by the hot deployment service. The deploy location can be overridden by specifying a location in the URL attribute of the URLDeploymentScanner configuration item.
| lib | Contains the dependency files required by the server.
| log | Contains the logs from the bootstrap logging service. The log directory is the default directory into which the bootstrap logging service places its logs, however, the location can be overridden by altering the log4j.xml configuration file. This file is located in the _conf_ directory.					
|===

The standalone Media Server uses a number of XML configuration
files that control various aspects of the server.
<xref linkend="tab-mms-standalone_core_configuration_file_set" />
describes the location of the key configuration files,
and provides a description of the


[[_tab_mms_standalone_core_configuration_file_set]]
.Core Configuration File Set
[cols="1,1", frame="all", options="header"]
|===
| File Name and Location | Description
| conf/bootstrap-beans.xml | Specifies which additional microcontainer deployments are loaded as part of the bootstrap phase. For a standard configuration, the bootstrap configuration files require no alteration.
| conf/mediaserver.xml | Main configuration file responsible for configure all aspects of the Media Server core. For in-depth details of this file please see chapter 3.
| conf/mgcp-conf.xml | Specifies the configuration for the MGCP controller.
| conf/log4j.properties | Specifies the Apache log4j framework category priorities and appenders used by the Media Server.
| deploy/server-beans.xml | Specified list of Java Beans necessary for bootstrapping the Media Server. For a standard configuration, the bootstrap configuration files require no alteration.
|===

[[_itms_writing_and_running_tests_against_the_media_server]]
=== Writing and Running Tests Against the Media Server

For information about the different kinds of tests that the Media Server provides, refer to http://groups.google.com/group/mobicents-public/web/mobicents-ms-tests[Writing and Running Tests Against RestComm MS]			 


