@startuml
state EXECUTING_REMOTE {
    [*] --> HALF_OPENING_REMOTE_CONNECTION : [no_remote_description]
    [*] --> OPENING_REMOTE_CONNECTION : [has_remote_description]
    HALF_OPENING_REMOTE_CONNECTION --> UPDATING_REMOTE_CONNECTION_MODE : connection_opened
    OPENING_REMOTE_CONNECTION --> UPDATING_REMOTE_CONNECTION_MODE : connection_opened
    UPDATING_REMOTE_CONNECTION_MODE --> REGISTERING_REMOTE_CONNECTION : connection_mode_updated
    REGISTERING_REMOTE_CONNECTION --> REGISTERED_REMOTE_CONNECTION : connection_registered
    REGISTERED_REMOTE_CONNECTION --> [*]
}

state ROLLBACK_REMOTE {
    [*] --> UNREGISTERING_REMOTE_CONNECTION : [is_registered]
    [*] --> CLOSING_REMOTE_CONNECTION : [not_registered]
    UNREGISTERING_REMOTE_CONNECTION --> CLOSING_REMOTE_CONNECTION : connection_unregistered
    CLOSING_REMOTE_CONNECTION --> CLOSED_REMOTE_CONNECTION : connection_closed
    CLOSED_REMOTE_CONNECTION --> [*]
}

state EXECUTING_LOCAL {
    [*] --> OPENING_FIRST_LOCAL_CONNECTION
    OPENING_FIRST_LOCAL_CONNECTION --> OPENING_SECOND_LOCAL_CONNECTION : connection_opened
    OPENING_SECOND_LOCAL_CONNECTION --> JOINING_LOCAL_CONNECTIONS : connection_opened
    JOINING_LOCAL_CONNECTIONS --> UPDATING_FIRST_LOCAL_CONNECTION_MODE : connections_joined
    UPDATING_FIRST_LOCAL_CONNECTION_MODE --> UPDATING_SECOND_LOCAL_CONNECTION_MODE : connection_mode_updated
    UPDATING_SECOND_LOCAL_CONNECTION_MODE --> REGISTERING_FIRST_LOCAL_CONNECTION : connection_mode_updated
    REGISTERING_FIRST_LOCAL_CONNECTION --> REGISTERING_SECOND_LOCAL_CONNECTION : connection_registered
    REGISTERING_SECOND_LOCAL_CONNECTION --> REGISTERING_LOCAL_CONNECTIONS : connection_registered
    REGISTERING_LOCAL_CONNECTIONS --> [*]
}

state ROLLBACK_LOCAL {
    [*] --> UNREGISTERING_FIRST_LOCAL_CONNECTION : [is_registered]
    [*] --> CLOSING_FIRST_LOCAL_CONNECTION : [not_registered]
    UNREGISTERING_FIRST_LOCAL_CONNECTION --> CLOSING_FIRST_LOCAL_CONNECTION : unregistered_connection
    CLOSING_FIRST_LOCAL_CONNECTION --> UNREGISTERING_SECOND_LOCAL_CONNECTION : closed_connection [is_registered]
    CLOSING_FIRST_LOCAL_CONNECTION --> CLOSING_SECOND_LOCAL_CONNECTION : closed_connection [not_registered]
    UNREGISTERING_SECOND_LOCAL_CONNECTION --> CLOSING_SECOND_LOCAL_CONNECTION : unregistered_connection
    CLOSING_SECOND_LOCAL_CONNECTION --> CLOSED_SECOND_LOCAL_CONNECTION : closed_connection
    CLOSED_SECOND_LOCAL_CONNECTION --> [*]
}

[*] --> VALIDATING_PARAMETERS : execute
VALIDATING_PARAMETERS --> EXECUTING_LOCAL : create_remote [create_pair]
VALIDATING_PARAMETERS --> EXECUTING_REMOTE : create_remote [create_single]
VALIDATING_PARAMETERS --> FAILED : failure, abort

EXECUTING_LOCAL -right> SUCCEEDED : success
EXECUTING_LOCAL --> ROLLBACK_LOCAL : failure, abort

EXECUTING_REMOTE -left> SUCCEEDED : success
EXECUTING_REMOTE --> ROLLBACK_REMOTE : failure, abort

ROLLBACK_REMOTE --> FAILED : rolled_back
ROLLBACK_LOCAL --> FAILED : rolled_back

SUCCEEDED --> [*]
FAILED --> [*]
@enduml