@startuml
[*] --> VALIDATING_PARAMETERS
VALIDATING_PARAMETERS --> EXECUTING : validated_parameters
VALIDATING_PARAMETERS --> FAILED : failure

EXECUTING --> FAILED : failure
EXECUTING --> SUCCEEDED : executed

SUCCEEDED --> [*]
FAILED --> [*]
@enduml