@startuml
interface AsyncNettyNetworkChannel
class RtpChannel
class RtpChannelInitializer

class RtpDemultiplexer
class RtpInboundHandler
class RtpEncoder

interface RtpSession
class RtpSessionImpl
class RtpSessionContext
class RtpSessionStatistics


interface RtpSessionFsm
interface RtpSessionFsmListener
class RtpSessionFsmBuilder
abstract class AbstractRtpSessionFsm
class RtpSessionFsmImpl
enum RtpSessionState
enum RtpSessionEvent
interface RtpSessionTransactionContext

interface JitterBuffer
class DtmfInput
class RtpInput
class RtpOutput

AsyncNettyNetworkChannel <|-- RtpChannel
RtpChannelInitializer -> RtpChannel : build pipeline
RtpChannel --> RtpDemultiplexer : DatagramPacket
RtpDemultiplexer --> RtpInboundHandler : RtpPacket
RtpInboundHandler --> RtpSession : incoming rtp
RtpEncoder <-- RtpChannel : write
RtpChannel <-- RtpSession : send

RtpSession <|-- RtpSessionImpl
RtpSessionImpl -> RtpSessionFsm
(RtpSessionImpl,RtpSessionFsm) .. RtpSessionFsmListener

RtpSessionImpl --> RtpSessionContext
RtpSessionContext --> RtpSessionStatistics

RtpSessionImpl <-- RtpOutput : outgoing RTP
RtpSessionImpl --> JitterBuffer : write
RtpSessionImpl --> DtmfInput : write
JitterBuffer --> RtpInput : wakeup
JitterBuffer <-- RtpInput : read

RtpSessionFsm <- RtpSessionFsmBuilder : builds
RtpSessionFsm <|-- AbstractRtpSessionFsm
AbstractRtpSessionFsm <|-- RtpSessionFsmImpl
RtpSessionState <-- RtpSessionFsm
RtpSessionEvent <-- RtpSessionFsm
RtpSessionTransactionContext <-- RtpSessionFsm
RtpSessionContext <-- RtpSessionFsmImpl
@enduml