@startuml
state OPENING {
[*] --> ALLOCATING
ALLOCATING --> BINDING : allocated
BINDING --> OPENED : bound
}

state NEGOTIATING {
[*] --> NEGOTIATING_FORMATS
NEGOTIATING_FORMATS --> CONNECTING : negotiated_formats
CONNECTING --> NEGOTIATED : connected
}

[*] --> IDLE
IDLE --> OPENING : open
IDLE --> CLOSED : close
OPENING --> OPEN : opened
OPENING --> CLOSED : close
OPEN --> NEGOTIATING : negotiate
OPEN --> CLOSED : close
NEGOTIATING --> ESTABLISHED : negotiated
NEGOTIATING --> CLOSED : close
ESTABLISHED --> NEGOTIATING : negotiate
ESTABLISHED --> CLOSED : close
@enduml