[[_s_event_packages]]
= MMS: Event Packages
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .

Announcement Package(A): `org.mobicents.media.server.mgcp.pkg.ann` 

.Announcement Package(A): 
[cols="1,1", frame="all", options="header"]
|===
| Signal Name
| Description


|===

For more information please see: https://tools.ietf.org/html/rfc3660#section-2.12	



`Advanced Audio Package(AU): org.mobicents.media.server.mgcp.pkg.au`		

.Advanced Audio Package(AU): 
[cols="1,1", frame="all", options="header"]
|===
| Signal Name
| Description





|===

For more information please see: https://tools.ietf.org/html/rfc2897  



`Trunk Package(T): org.mobicents.media.server.mgcp.pkg.trunk`		

.Trunk Package(T): 
[cols="1,1", frame="all", options="header"]
|===
| Signal Name
| Description





|===

For more information please see: https://tools.ietf.org/html/rfc3660#section-2.3	



Dtmf Package(D): `org.mobicents.media.server.mgcp.pkg.dtmf`		

.Dtmf Package(D): 
[cols="1,1", frame="all", options="header"]
|===
| Signal Name
| Description

















|===

For more information please see: https://tools.ietf.org/html/rfc3660#section-2.2 



`Signal List Package (SL): org.mobicents.media.server.mgcp.pkg.sl `		

.Signal List Package (SL): 
[cols="1,1", frame="all", options="header"]
|===
| Signal Name
| Description


|===

For more information please see: https://tools.ietf.org/html/rfc3660#section-2.8


== List of supported packages per Endpoint

Configuration of supported packages and events can be done through the mgcp-conf.xml configuration file that is located in the [path]_conf_ directory. 

The table belows shows supported packages and the related enabled endpoints 

.List of Supported Packages per Endpoint
[cols="1,1", frame="all", options="header"]
|===
| Package name
| Endpoints





|===